version: '3.7'

services:
  ui:
    build:
      context: './'
      dockerfile: './src/web/ui/Dockerfile'
    image: 'simplyvc/panic_polkadot_ui:2.4.0'
    volumes:
      - './config:/opt/panic_polkadot/config'
      - './src/web/ui/sessions:/opt/panic_polkadot/src/web/ui/sessions'
      - './src/web/ui/certificates:/opt/panic_polkadot/src/web/ui/certificates'
    ports:
      - '${UI_HOST_PORT}:9000'
    restart: always

  redis:
    image: 'redis'
    ports:
      - "${REDIS_HOST_PORT}:6379"
    restart: always

  mongo:
    image: 'mongo'
    ports:
      - "${MONGO_HOST_PORT}:27017"
    restart: always

  alerter:
    build: .
    image: 'simplyvc/panic_polkadot:2.3.0'
    volumes:
      - './config:/opt/panic_polkadot/config'
      - './logs:/opt/panic_polkadot/logs'
    restart: always